### ISSUE TITLE
Alignement between MIDI and MP3 from MIDI files

### ISSUE THREAD

**Issue by Kolia2503** [aheidt/dtw-app#2]
I'm sorry, I have another problem.
When I load all my files, I realized that the MIDI file isn't aligned with the two other files.
MIDI file lasts about 6 minutes, and the converted midi in mp3 also of course. Also the original mp3 file.

But here, it appears like if the MIDI file should last only the half of its child mp3. But bars of course overlap lines 4 and 5 like if they were lasting the same amount of time. And DTW fits only the original mp3 with the mp3 from midi.

The screen was made shortly after applying DTW algorithm.
![fit](https://user-images.githubusercontent.com/102409768/160243700-4e63673d-769e-4e18-aeb1-9d16829b0b18.png)

Python does not states any errors.

What could be the source of the problem please?

**Comment by aheidt** [comment]
I also had some issues sometimes with loading the midi, it appeared that the time was cut in half, from 6 minutes to 3 minutes, haven't figured out how to fix it.
Here is a workaround:

1. load files
2. manually stretch the midi (insert a bar at 180 in the midi plot and drag it to 360)
3. export the midi
4. create audio file from new midi
5. restart the app and load all files again (this time with the new midi & audio from new midi)

For the DTW to properly work, the length of the midi and the length of the audio should be roughly equal, it doesn't like big jumps.

Chart 4 & 5 should be aligned at all times, from the moment you loaded the files to the end.

**Comment by Kolia2503** [comment]
Ok, I dragged the bar, 
A new bar was inserted at: 566 86 | 180.3067867724868
closest bars to 367.6219645502646 are: 0 and 382.27587301587306
A bar was moved from: 566 86 to 1154 64 | 180.3067867724868 -> 367.6219645502646

but the midi didn't want to export. (I had sometimes this problem already before)

Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Kolia\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\Kolia\Desktop\midi\dtw-app-main\app.py", line 489, in on_save_midi
    MidiIO.export_midi(df_midi=self.app.data_5.df_midi, outfile=self.app.data_5.outfile, time_colname="time abs (sec)")
  File "C:\Users\Kolia\Desktop\midi\dtw-app-main\dtw.py", line 302, in export_midi
    file.save(outfile)
  File "C:\Users\Kolia\AppData\Local\Programs\Python\Python310\lib\site-packages\mido\midifiles\midifiles.py", line 432, in save
    self._save(file)
  File "C:\Users\Kolia\AppData\Local\Programs\Python\Python310\lib\site-packages\mido\midifiles\midifiles.py", line 445, in _save
    write_track(outfile, track)
  File "C:\Users\Kolia\AppData\Local\Programs\Python\Python310\lib\site-packages\mido\midifiles\midifiles.py", line 251, in write_track
    data.extend(encode_variable_int(msg.time))
  File "C:\Users\Kolia\AppData\Local\Programs\Python\Python310\lib\site-packages\mido\midifiles\meta.py", line 112, in encode_variable_int
    raise ValueError('variable int must be a positive integer')
ValueError: variable int must be a positive integer

I use Python 3.10 (64-bit)

Edit: OK, I figured that it works only with MIDI with one track.

And I understood why the MIDI file apperars with different lenght at the beginning: when you export it unchanged, it keeps a 120 beat with 4/4 from beginning to the end, regardless of initial setup.

**Comment by aheidt** [comment]
Yes, one track only. And you're right, also on import it doesn't properly read the tempo, it always assumes 120 beat 4/4 on import & export. I'll update the description to avoid confusion, my bad^^

**Comment by Kolia2503** [comment]
Ok, good, thank you very much!
